### ISSUE TITLE
AoT compatible with Angular CLI

### ISSUE THREAD

**Issue by kolkov** [ui-router/core#11]
Hi! Is ui-router compatible with AoT compiler from CLI?
```
@NgModule({
  imports: [
    BrowserModule,    
    UIRouterModule.forRoot({     
      otherwise: { state: 'public.home', params: {} },
      useHash: false,
      //configClass: MyUIRouterConfig
    }),
  ],
  declarations: [
    AppComponent
  ],
  providers: [
  ],
  bootstrap: [ UIView ]
})
export class AppModule {}
```
I get this error:
![image](https://cloud.githubusercontent.com/assets/3740898/21073128/b664252c-bee7-11e6-9d39-4ac9ef91fd1c.png)

**Comment by aitboudad** [comment]
see https://github.com/ui-router/ng2/pull/13

**Comment by christopherthielen** [comment]
Closing due to https://github.com/ui-router/ng2/pull/13

**Comment by christopherthielen** [comment]
note: `beta.5` is expected to have AoT and angular-cli support with lazy loading.
