### ISSUE TITLE
Sticky states + "orphan" state + onExit = transition error

### ISSUE THREAD

**Issue by what-is-a-crow** [ui-router/core#111]
We're attempting to upgrade ui-router to the latest supported version (from 0.2.18) and are having issues navigating from parent-less (in our case, fly-out / modal) states. Many of our application's forms are in such states and, on successful submission, we tend to do a `$state.go("normal-state", {}, { reload: true })` to be sure that the user's changes are reflected in the previous state. If the "to" state has an `onExit` defined, however, we get the following ui-router exception: `Transition Rejection($id: 0 type: 6, message: The transition errored, detail: TypeError: Cannot read property 'reduce' of undefined)` with the underlying error happening at `ResolveContext.getTokens`.

I was able to create a Plunker example to reproduce: http://plnkr.co/edit/PdCjLhosY9LE9aOzLTfA

Our suspicion is `src/path/pathUtils.ts:187` where an unsuccessful lookup returns undefined instead of an empty array but it could be something further up the stack.

**Comment by christopherthielen** [comment]
This might be a difficult bug to fix in sticky-states.
here's a workaround for now: http://plnkr.co/edit/998o5W3o3yLqbkykJFy2?p=preview

**Comment by christopherthielen** [comment]
This issue was moved to ui-router/sticky-states#30
