### ISSUE TITLE
StateService transition is returning null

### ISSUE THREAD

**Issue by bouncehead13** [ui-router/core#145]
I am having trouble getting access to the transition data from within the state service.

**Scenario**:
I go directly to a page which loads a component. In that component, I'm using `this.state.transition` to get access to the resolved tokens.

**Problem**:
What I have learned is the transition within state is `null`. Only if I go to this page navigating from somewhere else does the transition object exist. From what I can tell, only on a hard refresh does the transition object not exist.

Can you help me understand if this is expected behavior or a bug? To me, navigating to the page for the first time is considered a transition and the transition object should exist.

**Comment by christopherthielen** [comment]
Sorry for the delay.

Which ui-router are you using? angularjs? angular? react? 

You should access the transition from the routed component.  Each framework has its own way of accessing the transition.

angularjs:

```js
controller: function($transition$) {
 
}
```

Angular:
```
class MyCmp {
  constructor(transition: Transition) {

  }
}
```


React:
```js
class MyCmp extends React.Component {
  constructor(props) {
    props.transition....
  }
}
```

**Comment by bouncehead13** [comment]
I'm using Angular.

Interesting. So are you suggesting to use Transition over the StateService? What I mean is...
Do Not:
```
class MyComp {
  constructor(state: StateService) {
    let transition = state.transition;
  }
}
```

Do:
```
class MyComp {
  constructor(trans: Transition) {
    let transition = trans;
  }
}
```

**Comment by christopherthielen** [comment]
@bouncehead13 exactly. `StateService.transition` is the *currently running* transition. By the time your component is rendered, the transition is usually over already.

**Comment by bouncehead13** [comment]
So when I do that I get `No provider for Transition!`. However the solution I have found is on app load, meaning no transition has really started yet, I rely on `uiRouter.globals.transition`. Anything after app load, I rely on the `Transition` object coming from the `onSuccess` hook. This has worked every time for me.
