### ISSUE TITLE
Match Future states

### ISSUE THREAD

**Issue by aitboudad** [ui-router/core#19]
When tying to access to `/account` which is lazy path it always redirect me to the `static_page`
```ts
export const app_states = [
    { name: 'account.**', url: '/account', lazyLoad: ... },
    { name: 'static_page', url: '/{name}', component: StaticPage },
]
```
to solve this the future states should be [registered](https://github.com/ui-router/core/blob/master/src/hooks/lazyLoad.ts#L113) with the same order of it's parent or changing the [matching rule](https://github.com/ui-router/core/blob/master/src/hooks/lazyLoad.ts#L50)

**Comment by christopherthielen** [comment]
I added a test for your scenario: https://github.com/ui-router/core/blob/f07b369818631ab4f4d454ec17a4f66947faebc7/test/urlRouterSpec.ts#L305-L326

**Comment by aitboudad** [comment]
Thanks!
