### ISSUE TITLE
Distributable in lib-esm should target es6, reduces bundle sizes

### ISSUE THREAD

**Issue by joeljeske** [ui-router/core#196]
Currently, the artifacts in `lib-esm` are using es modules, but they are built using ES5 target in TypeScript. This should be corrected as the equivalent ES6 code is often a fair bit smaller. Converting a ES Class to ES5 often leads to considerable bloat with all the `Class.prototopes.method = ...` and the `Object.defineProperty(...)` and all. 

It appears the `compile` script in pacakge.json could be modified to pass `--target es6` to tsc for the second build. 
https://github.com/ui-router/core/blob/master/package.json#L7

In my estimates, the `_bundle/ui-router-core.min.js` size could be reduced from 91 KB to 77KB. 

Please advise if this is something that would be acceptable or if it might break things. I like this project, and would like it even more if it could shed some weight :)

**Comment by vort3xxx** [comment]
Would that change break IE11 support?

**Comment by joeljeske** [comment]
Perhaps, but this would only affect lib-esm which already includes modules not supported by IE11 and needs to be rewritten by the consuming application. The consuming application could still transpile down for their needs.

I did give the example of the change in bundle size, but ideally those would still be valid IE11 compatible.
