### ISSUE TITLE
Req: Make glob hook match criteria to match states without dots.

### ISSUE THREAD

**Issue by mr-moon** [ui-router/core#205]
Personally, I don't like dots in state names, so I explicitly nest my states by setting a `parent`.

```
.state('top', {url: '/'})
.state('bottom', {url: '/bottom', parent: 'top'});
```
But then, mighty `HookMatchCriteria` with glob of `top.**` is not matching my `bottom` state. Of course, I can use criterion as:

```
state => {
    while (state = state.parent) {
        if (state.name === 'top') {
            return true;
        }
    }
    return false;
}
```

But that's sub-optimal? Or am I missing something?

Thanks

**Comment by wawyed** [comment]
Have you tried using the includes object on the StateObject?
```
state => {
    return state.includes.top;
}
```

**Comment by christopherthielen** [comment]
I think it's a reasonable idea https://github.com/ui-router/core/issues/5
My only concern is wondering if it would break any existing code, or if would be 100% backwards compatible.
