### ISSUE TITLE
Suggestion: inverted glob patterns in transition hooks

### ISSUE THREAD

**Issue by Septh** [ui-router/core#21]
Currently, if I wanted to write a transition hook for a specific state, I'd target this state like so:

````js
{ to: 'mystate' }
````

But if I needed a transition for every state _but_ a specific one:  

````js
{ to: function(state) { return state.name != 'mystate' } }
````

Ideally, the glob pattern matcher would accept something like:

````js
{ to: '!mystate' }  // Reject 'mystate'
````

This would allow interesting things like ignoring a whole path in the tree:

````js
{ to: '!mystate.**' } // Match anything that is NOT under 'mystate'
````

What do you think?

**Comment by christopherthielen** [comment]
I love the idea.
