### ISSUE TITLE
window.console errors in IE9

### ISSUE THREAD

**Issue by lukaszprus** [ui-router/core#285]
I am running an app which uses [https://github.com/angular-ui/ui-router/releases/tag/1.0.20](url) and I get this error in IE9: 

![screenshot from 2018-11-16 09 57 44](https://user-images.githubusercontent.com/2707997/48588296-75708d00-e986-11e8-96de-65b0965a3aee.png)

![screenshot from 2018-11-16 09 56 42](https://user-images.githubusercontent.com/2707997/48588270-5114b080-e986-11e8-925b-10c321d21e68.png)

It looks like you are using many `console.log` statements in `core/src/common/trace.ts` and take it for granted whereas console is undefined in IE9 (unless developer tools are open)

This is a known issue: [https://stackoverflow.com/questions/5472938/does-ie9-support-console-log-and-is-it-a-real-function](url)

**Comment by christopherthielen** [comment]
Interestingly, this code was [intended to work with IE9](https://github.com/ui-router/core/pull/85/files)
