### ISSUE TITLE
UI-Router not working with AOT

### ISSUE THREAD

**Issue by hkgupta** [ui-router/core#288]
I am using @uirouter/angular-hybrid package version "4.0.0" in my project. It works in JIT mode absolutely fine but after compiling the ng 2 application to AOT, the routing to the ng2 components have stopped working. When I am trying to route to the the ng2 component route it is not throwing any error and even statechangesuccess is getting invoked but ui-view is coming as empty. 
<div ui-view="" class="" style=""><ui-view-ng-upgrade name="$default" ng-version="5.2.9"><ui-view>
    
    
  </ui-view></ui-view-ng-upgrade></div>
Please help.

**Comment by christopherthielen** [comment]
Here's an the example app repo which uses AoT: https://github.com/ui-router/sample-app-angular-hybrid

**Comment by dblVs** [comment]
@hkgupta we use ui-router in a hybrid app and we use AoT

**Comment by wawyed** [comment]
Make sure you don't have anything that can't be analysed statically in your route definitions. The router itself does support AOT, so something in your project is what is causing the issue.
