### ISSUE TITLE
HookMatchCriteria compile error in TypeScript with strict null checks

### ISSUE THREAD

**Issue by schoel-bis** [ui-router/core#33]
Compiling a typescript application with strict null checks enabled will produce a number of errors due to the definition of HookMatchCriteria:

> ERROR in /home/schoel/Projekte/javascript/i3ge/node_modules/ui-router-core/lib/transition/interface.d.ts
> (735,5): error TS2411: Property 'to' of type 'string | boolean | Predicate<State> | undefined' is not assignable to string index type 'string | boolean | Predicate<State>'.
> 
> ERROR in /home/schoel/Projekte/javascript/i3ge/node_modules/ui-router-core/lib/transition/interface.d.ts
> (737,5): error TS2411: Property 'from' of type 'string | boolean | Predicate<State> | undefined' is not assignable to string index type 'string | boolean | Predicate<State>'.
> 
> ERROR in /home/schoel/Projekte/javascript/i3ge/node_modules/ui-router-core/lib/transition/interface.d.ts
> (739,5): error TS2411: Property 'exiting' of type 'string | boolean | Predicate<State> | undefined' is not assignable to string index type 'string | boolean | Predicate<State>'.
> 
> ERROR in /home/schoel/Projekte/javascript/i3ge/node_modules/ui-router-core/lib/transition/interface.d.ts
> (741,5): error TS2411: Property 'retained' of type 'string | boolean | Predicate<State> | undefined' is not assignable to string index type 'string | boolean | Predicate<State>'.
> 
> ERROR in /home/schoel/Projekte/javascript/i3ge/node_modules/ui-router-core/lib/transition/interface.d.ts
> (743,5): error TS2411: Property 'entering' of type 'string | boolean | Predicate<State> | undefined' is not assignable to string index type 'string | boolean | Predicate<State>'.
 
This is because the type of the string keyed property (`[key: string]: HookMatchCriterion`) has to match the type any other property in the interface. All other properties are optional, though, and thus of type `HookMatchCriterion | undefined`. Changing the type of the string keyed property to `HookMatchCriterion | undefined` resolves the issue.

**Comment by helmutschneider** [comment]
@christopherthielen Not sure why this was closed - the issue still exists in the current code:
```typescript
export interface HookMatchCriteria {
  [key: string]: HookMatchCriterion;
  to?: HookMatchCriterion | undefined;
  from?: HookMatchCriterion | undefined;
  exiting?: HookMatchCriterion | undefined;
  retained?: HookMatchCriterion | undefined;
  entering?: HookMatchCriterion | undefined;
}
```
`[key: string]: HookMatchCriterion` is typed as non-undefined which causes the compilation to fail on all the optional properties. The code should probably read:
```typescript
export interface HookMatchCriteria {
    [key: string]: HookMatchCriterion | undefined;
    to?: HookMatchCriterion;
    from?: HookMatchCriterion;
    exiting?: HookMatchCriterion;
    retained?: HookMatchCriterion;
    entering?: HookMatchCriterion;
}
```

**Comment by mrahhal** [comment]
Also still facing this.

**Comment by AnimaLupi** [comment]
Same issue here.

**Comment by mrahhal** [comment]
Right now this is the only blocker for me to use the "strict" option. A bit frustrating.

**Comment by gaui** [comment]
When is 0ae585e going to be released? I added that patch and everything compiles.

**Comment by gaui** [comment]
Chris 🙏

**Comment by christopherthielen** [comment]
New core and angularjs releases tonight
