### ISSUE TITLE
Do not log TransitionRejection when the transition is ABORTED.

### ISSUE THREAD

**Issue by christopherthielen** [ui-router/core#35]
https://github.com/ui-router/core/blob/64fbfff15433c80db042a08522d5f8cfe4d509ff/src/state/stateService.ts#L366-L373

```js
    const rejectedTransitionHandler = (transition: Transition) => (error: any): Promise<any> => {
      if (error instanceof Rejection) {
        if (error.type === RejectType.IGNORED) {
          // Consider ignored `Transition.run()` as a successful `transitionTo`
          router.urlRouter.update();
          return services.$q.when(globals.current);
        }

        const detail: any = error.detail;
        if (error.type === RejectType.SUPERSEDED && error.redirected && detail instanceof TargetState) {
          // If `Transition.run()` was redirected, allow the `transitionTo()` promise to resolve successfully
          // by returning the promise for the new (redirect) `Transition.run()`.
          let redirect: Transition = transition.redirect(detail);
          return redirect.run().catch(rejectedTransitionHandler(redirect));
        }

        if (error.type === RejectType.ABORTED) {
          router.urlRouter.update();
          // Fall through to default error handler
        }
      }

      let errorHandler = this.defaultErrorHandler();
      errorHandler(error);

      return services.$q.reject(error);
    };

```

Current behavior is to log ABORTED rejections.  Enough people have requested not to log, or been confused about how to mute them.  We should change so we no longer fall through to the default error handler.

**Comment by christopherthielen** [comment]
Closed by b07a24b992aaeb8062e52e32f72f4f70a1e38d98

**Comment by seanhodges-tw** [comment]
Hi, issue https://github.com/angular-ui/ui-router/issues/3302 refers here, should this fix apply to Angular 1 ui-router too?

**Comment by iwan-uschka** [comment]
I try to abort a transition without having an error log entry, i cannot use `transition.abort()` because i have to wait for a user input ("unsaved changes. continue?") so i return a promise.

```
      $transitions.onExit({exiting: 'main.settings'}, function(transition) {      
        var deferred = $q.defer();
        
        // promise testing
        $timeout(function(){
          // here i need to create a Rejection Object with type = RejectType.ABORTED 
          deferred.reject(false);
        }, 500);

        return deferred.promise;
      });
```

If i reject the promise, i get the error log entry, because i don't know, how to create a `Rejection` with a `RejectType.ABORTED` in my controller. How can i get access to the Rejection Class?

Or is there any other way, how i can abort a transition asynchronously and without creating a error log entry?

Using Angular 1.5.1 and ui-router 1.0.5.

Thanks

**Comment by DzmVasileusky** [comment]
@iwan-uschka It's because this fix was applied for Angular2-5 ui-router version only.

**Comment by ranst91** [comment]
Any plans on fixing it for Angularjs?
