### ISSUE TITLE
License clash MIT vs CC BY-SA 3.0

### ISSUE THREAD

**Issue by githendrik** [ui-router/core#350]
Hi,

we're using ui-router for a couple of angular projects within the enterprise context. Our FOSS team has made us aware of the following license clash:

angular-ui-router is licensed under MIT. However, the source file `hof.ts` mentions a snippet from stackoverflow - which is automatically licensed under CC BY-SA 3.0 / https://stackoverflow.com/help/licensing

CC BY-SA 3.0 requires other projects to also use the CC BY-SA 3.0 license, or get permission of the creator to use it under a different license.

You might want to look into this with the creator of the snippet, or re-create the part of code.

**Comment by christopherthielen** [comment]
@githendrik done

**Comment by githendrik** [comment]
Perfect, thanks!
