### ISSUE TITLE
Custom parameter type’s encode function is not called for array params

### ISSUE THREAD

**Issue by rluba** [ui-router/core#37]
**The problem**
1. Define a custom type [using the `definitionFn` instead of the `definition` object](https://ui-router.github.io/ng1/docs/latest/classes/url.urlmatcherfactory.html#type)
2. Use this new type for a state parameter that _does not_ explicitly set [`array: false`](https://ui-router.github.io/ng1/docs/latest/interfaces/params.paramdeclaration.html#array)
3. **The parameter type’s [`encode` function](https://ui-router.github.io/ng1/docs/latest/interfaces/params.paramtypedefinition.html#encode) is never invoked during state transitions, so the parameter is not encoded correctly.**

**The reason**
Because the parameter does not declare `array: false` its type is wrapped into an `ArrayType` during state declaration – that’s **before the type’s `definitionFn` is invoked**.

But `ArrayType` defines its `encode` function (and others) [based on the wrapped type’s functions **at the time when `ArrayType` is instantiated**](https://github.com/ui-router/core/blob/fec3bb1b29ebb3ff6c728de3295e71760c207f8b/src/params/paramType.ts#L139-L143). `ArrayType` stores a reference to the old `encode` function (which was undefined, so it’s the `identity` function) instead of looking up the actual function when `ArrayType.encode` is called.

Later, [the type’s `definitionFn` is invoked and redefines the `encode` function](https://github.com/ui-router/core/blob/64fbfff15433c80db042a08522d5f8cfe4d509ff/src/params/paramTypes.ts#L236-L242), but the array params still reference the identity function.

**The solution**
* Either defer the instantiation of `ArrayType` until after all `definitionFn`s were invoked (probably compilcated)
* Or define the `ArrayType`’s functions based on the run-time value of the wrapped type’s functions instead of capturing them locally.

**Comment by christopherthielen** [comment]
I appreciate the detailed bug report!
