### ISSUE TITLE
If a transition to a particular state+params is pending, attempting to go to that state+params again should be a no-op

### ISSUE THREAD

**Issue by 00dani** [ui-router/core#42]
In the current codebase, attempting to go to a state+params identical to your current state+params is a no-op. This is good and makes sense, since there's nothing meaningful to do to transition from your current state+params to your current state+params.

However if you attempt to go to a different state+params, such as by clicking on a `ui-sref`, a transition is always created and ui-router starts resolving the necessary data. This causes a problem if the user tries to click the same `ui-sref` *twice* or more - ui-router will queue up a bunch of identical transitions, waste time retrieving the same resolve data repeatedly, and take much longer to actually switch to the new state.

A request to transition to a state should therefore be ignored if *either* the requested state is exactly the current state *or* it is exactly the destination state for the current transition.

**Comment by mrop** [comment]
Great this has been solved, specifically for the new behavior of aborting a state change:  "Now, aborted transitions do not trigger the `defaultErrorHandler`"
