### ISSUE TITLE
Non-root base causing infinite redirect

### ISSUE THREAD

**Issue by Schlesiger** [ui-router/core#44]
I am trying to host a UI-Router project with a non-root path in the `<base>` tag:
https://wallzero.gitlab.io/ui-router-react-digest/
(I suggest observing with Chrome since it will handle the `Uncaught RangeError: Maximum call stack size exceeded` without crashing)

UI-Router is then configured to redirect to TabA state. However, with a non-root base, an additional `/` preceeds the route `/taba` resulting in an infinite redirect between `/taba` and `//taba`. When it finally stops, the url is https://wallzero.gitlab.io/ui-router-react-digest/

I've tried both `<base href="/ui-router-react-digest/">` and `<base href="/ui-router-react-digest">`; with and without the trailing slash. It appears the urlRouter.otherwise function is prepending a `/`. I've tried the following which all produce the same result:

```
router.urlRouter.otherwise('/taba');
```

```
router.urlRouter.otherwise('taba');
```

```
router.urlRouter.otherwise(() => {
  return '/taba';
});
```

```
router.urlRouter.otherwise(() => {
  return 'taba';
});
```

Also, a root `<base href="/">` works just fine.

You can run my project yourself: https://gitlab.com/wallzero/ui-router-react-digest/tree/master. Run via `npm install && npm run build:demo:gitlab && npm run start:demo:dev:gitlab`.

**Comment by Schlesiger** [comment]
Sorry I didn't see the issue you raised with systemjs. It's probably why: https://github.com/systemjs/systemjs/issues/1609

**Comment by christopherthielen** [comment]
it looks like you're bundling using webpack, so probably not related.

I think we fixed some issues with base path in ui-router-core recently. 

I tried testing with builds from master, but after installing your demo and loading up http://127.0.0.1:8090/ the app doesn't load properly (the catchall rule is serving up the index file for all the `./bundle/*.js` links and I'm not familar with your build setup

**Comment by Schlesiger** [comment]
Thanks! I will look into my demo this weekend and investigate the issue. I will also be trying the latest 5.0.0-pre.1.

**Comment by Schlesiger** [comment]
After upgrading to latest I also cleaned up my `otherwise()` function, returning state instead of a url, and the infinite redirect was resolved.
