### ISSUE TITLE
child states missing when lazy loading 

### ISSUE THREAD

**Issue by christopherthielen** [ui-router/core#46]
_From @spyro92 on March 17, 2017 1:9_

This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.0-rc.1

# Bug Report

#### Current Behavior:

When lazy loading states, any states registered in modules that are dependencies to the module being lazy loaded will not be registered.

in the example: lazy.foo is being registered, but not lazy.bar

it seems to be a timing issue, if you remove the dependency on lazy.bar from the module 'lazy' the state will be registered.

#### Expected Behavior:

lazy.bar and lazy.foo should be registered

#### Link to Plunker that reproduces the issue:

http://plnkr.co/edit/IfxBMmsZgKVAyxSZ7w0g?p=info

_Copied from original issue: angular-ui/ui-router#3375_

**Comment by christopherthielen** [comment]
Thank you for the excellent bug report with plunker

**Comment by christopherthielen** [comment]
This is the same bug as https://github.com/ui-router/ng2/issues/40 and needs to be fixed in ui-router/core

**Comment by spyro92** [comment]
Thanks for your quick work on this!
Will ui-router/core v5.0.0 be going live with angular-ui/ui-router 1.0.0-rc.2?

**Comment by christopherthielen** [comment]
Yes, but it will probably be 1.0.0 final.
