### ISSUE TITLE
uiCanExit also called for redirected states

### ISSUE THREAD

**Issue by kdbruin** [ui-router/core#51]
[Using UI-Router 1.0]

I have a parent state with several child states to handle a tabbed view. The parent state redirects to the first child state using a `redirectTo` property.

In an unrelated state I have a component with a uiCanExit function in the controller that shows a confirmation dialog when there is unsaved data (with cancel, discard and save). When I press discard I resolve the dialog promise to true but the confirmation dialog is displayed again. To prevent this I need to make sure that the conditions for displaying the dialog are not met.

Is this a bug or intended feature?

**Comment by christopherthielen** [comment]
I think this was fixed in ui-router for angularjs 1.0.0-rc.2

https://github.com/angular-ui/ui-router/issues/3308

https://github.com/angular-ui/ui-router/commit/7a086ee0d6be24337b8441464d7c2f5b8524401f
