### ISSUE TITLE
Version 6.0.2 breaks using ui-router core on Node.js without a browser

### ISSUE THREAD

**Issue by cschwaderer** [ui-router/core#510]
I'm using ui-router core as an NPM module in an Node.js application (as being advised here https://stackoverflow.com/questions/44428275/parsing-ui-router-states-to-urls-without-angular by 
@christopherthielen )
Now, it seems this use case breaks in version 6.0.2 since commit https://github.com/ui-router/core/commit/9c8579d introduces a reference to `document` - which is, naturally, not present in Node.js, so the application breaks.

> /node_modules/@uirouter/core/lib/common/safeConsole.js:23
>     var isIE9 = document && document.documentMode && document.documentMode === 9;
>                 ^
> 
> ReferenceError: document is not defined
>     at getSafeConsole (node_modules/@uirouter/core/lib/common/safeConsole.js:23:17)
>     at Object.<anonymous> (node_modules/@uirouter/core/lib/common/safeConsole.js:34:23)

Steps to reproduce:

- Create a package.json file with the content: 
```
{
  "name": "uirouter603test",
  "dependencies": {
    "@uirouter/core": "6.0.3"
  }
}
```

- run `npm install`

- create a file app.js with just the line `var uiRouterCoreModule = require('@uirouter/core');`

- run `node app.js`

**Comment by christopherthielen** [comment]
published [6.0.4](https://github.com/ui-router/core/releases/tag/6.0.4)
