### ISSUE TITLE
<base> Tag Breaks Path Resolve

### ISSUE THREAD

**Issue by Schlesiger** [ui-router/core#54]
With `@uirouter/react@0.5.0` I've been able to upgrade to the latest. I fixed the [Infinite Redirect](https://github.com/ui-router/core/issues/44) (my fault) and the [History Push Error](https://github.com/ui-router/core/issues/45) seems to be resolved with the upgrades, so I can now at least demo the project. Again, the url is: https://wallzero.gitlab.io/ui-router-react-digest/

Now it seems `ui-router` does not work with the `<base>` tag - even if the `<base>` tag doesn't contain an `href`. With the `<base>` tag, every route transition triggers `otherwise()`. Both `go()` and a manual url will trigger `otherwise()`. In the demo you'll see it is stuck on `taba`. Selecting `tabb` fails to resolve the route and triggers `otherwise()`, making it return back to the resolve state, `taba`. I'm not sure why `otherwise()` is triggered, because if I call `router.stateService.go()` inside `resolve()`, it will complete without calling `otherwise()` again.

I've also noticed if I use a `<base>` tag, I have to remove the prepended `/` from my root route. If I don't, an extra `/` is shown after the `<base>`'s `href` - like in the demo.

If I run locally without the `<base>` tag, and return the prepended '/' to my root route, everything works properly. However, then I can no longer run on any path other than root `/`.

**Comment by Schlesiger** [comment]
I'm still not sure why state transition is alwayst triggering `otherwise()` when the `<base>` tag is included. For now, I tried to resolve the state myself inside `otherwise()`. After some trial and error, it also appears `{_baseHref}` is included in the url resolution and fails. If I remove the `{_baseHref}`, for example. '<del>/ui-router-react-digest/</del>taba', the path is resolved correctly. Here's what I ended up with:

```javascript
router.urlRouter.otherwise((found, route) => {
  const resolve = router.stateService.get().filter((state) => {
    return state.$$state().url &&
      state.$$state().url.exec(route.path.replace(router.locationConfig._baseHref, ''));
  })[0];

  return {
    state: resolve ? resolve.name : shortName + '.tabs.' + tabs[0].name
  };
});
```

**Comment by telekid** [comment]
@Schlesiger setting `<base>` causes `otherwise()` to trigger on each transition for me as well. In my case, I could work around the issue by simply setting the URL of my root state to my desired `<base>` url (e.g. `{ url: '/theapp', name: 'app' }` and removing `<base>` altogether. Not sure if this is recommended practice, and obviously won't work in all cases, but seems to work for me.

**Comment by Schlesiger** [comment]
Thanks @telekid for replying! I am glad to know I am not the only one. Your solution is definitely another option in most cases. However, my project is a React component built on top of `ui-router/react` with prepopulated routes - including `otherwise()`. While it may be possible for users to override the already defined `otherwise()`, it's an added complexity. The whole point of my component is to alleviate much of the typical boilerplate when starting with a navigable UI. My hacky `otherwise()` logic still works and I'll stick with that for now.

The real solution to fix the bug where `otherwise()` is called on every transition when `<base>` is set.

**Comment by christopherthielen** [comment]
Please try again with `@uirouter/react@0.5.2`

**Comment by Schlesiger** [comment]
Looks good! I removed my previous additional logic to `otherwise()` and everything is working:
https://wallzero.gitlab.io/ui-router-react-digest

Thanks!
