### ISSUE TITLE
[Transition][memory leak] Dispose unused transition

### ISSUE THREAD

**Issue by aitboudad** [ui-router/core#55]
part of https://github.com/ui-router/angular/issues/21

I did some debugging and I noticed that the issue is resolved if I reset `_treeChanges` when starting a new transition in [Transition::startTransition](https://github.com/ui-router/core/blob/master/src/transition/transition.ts#L671)

```js
var oldTransition = globals.transitionHistory.dequeue();
if (oldTransition) {
  oldTransition.promise.then(
    () => oldTransition._treeChanges = {},
    () => oldTransition._treeChanges = {},
 );
}
```

**Comment by attrobit** [comment]
when will this bug be fixed?

**Comment by christopherthielen** [comment]
reopened per uirouter/angularjs comment https://github.com/angular-ui/ui-router/issues/3603
