### ISSUE TITLE
is AOT supported?

### ISSUE THREAD

**Issue by p3pp8** [ui-router/core#572]
As of subject: Is AOT supported? I'm having some trouble using the UIRouter with angular AOT compilation. It simply does not import any dependency, no states or stateService available to be injected. Any help really appreciated!

Greets

**Comment by christopherthielen** [comment]
I assume you're asking about https://github.com/ui-router/angular (this repo is the framework agnostic `core` repo).  Yes, if you look at the [Angular Sample App](https://github.com/ui-router/sample-app-angular) you'll see an example using AOT and Angular 9.  If you go through the sample app commits, you can see AOT examples working with prior releases of Angular as well.
