### ISSUE TITLE
Ability to set defaultHrefOpts globally

### ISSUE THREAD

**Issue by cloakedninjas** [ui-router/core#614]
I've found an issue whereby when a user enters the site with an anchor link in the URL `domain.com/app/page#section` The anchor part `#section` is appended to all URLs being output by `ui-sref` e.g. `domain.com/app/home#section` & `domain.com/app/contact#section`

By stepping through the library code, I found that the root state `{state: ''}` is being given the param:

```
params: {
  '#': Param(...)
}
```

And then in [stateService.href()](https://github.com/ui-router/core/blob/795eb41141d3e1523e5124c8a9fd3e4e5e469b47/src/state/stateService.ts#L510) that param is inherited all the way down my chain of states

I'm not sure if this is a bug, something is misconfigured, or an issue with the app I'm working with  but I have found that if I change the default value `inherit: true` to `false` this issue goes away.

```
"@uirouter/angular": "^6.0.1",
"@uirouter/angular-hybrid": "^10.0.1",
"@uirouter/angularjs": "^1.0.25",
"@uirouter/core": "^6.0.4",
"@uirouter/rx": "^0.6.5",
```
(any pointers appreciated)

**Comment by christopherthielen** [comment]
could you write a transition hook to clear the parameter on startup?

```
  router.transitionService.onBefore({ from: "" }, transition => {
    const params = transition.params();
    if (params["#"] !== null) {
      const targetState = transition
        .targetState()
        .withParams({ ...params, "#": null });
      return transition.redirect(targetState);
    }
  });
```

Since it's the initial transition, the router won't change the URL, but it should be cleared when the user follows an UISref
