### ISSUE TITLE
WebWorker compatibility

### ISSUE THREAD

**Issue by Sifawm** [ui-router/core#62]
In my team, we are trying to use webworkers but @angular/core raise an error.

Instead of `window`, `self` is a reference for Window or WebWorker.

![image](https://user-images.githubusercontent.com/5755632/27295881-d15c8fb8-551e-11e7-9fc0-018210ab6c26.png)

Plnkr: [https://embed.plnkr.co/V5p6igk2POXUhOMwH7iz/](https://embed.plnkr.co/V5p6igk2POXUhOMwH7iz/)

**Edit: plnkr updated**

**Comment by christopherthielen** [comment]
Related: https://github.com/ui-router/angular/issues/134
