### ISSUE TITLE
strictNullChecks causing compiler error

### ISSUE THREAD

**Issue by corsen2000** [ui-router/core#63]
`
Property 'from' of type 'string | boolean | Predicate<StateDeclaration> | undefined' is not assignable to string index type 'string | boolean | Predicate<StateDeclaration>'.
`

I get this error when enabling `strictNullChecks`. I've worked around it with the `skipLibCheck` option in my `.tsconfig.json`. I see [some work was done](https://github.com/ui-router/core/commit/d92d4d5) to better support `strictNullChecks`, but I am still having an issue.

Thank you for your time.

**Comment by christopherthielen** [comment]
Closed by https://github.com/ui-router/core/commit/0ae585e9fe7fb6dd5bf052450435908a3e21fbdf
