### ISSUE TITLE
Url matching by priority critical issue: sorting is unstable on chrome (and possibly others)

### ISSUE THREAD

**Issue by mrahhal** [ui-router/core#66]
I spent a good full day debugging this problem, almost drove me insane.

[Plunkr that illustrates the issue.](http://plnkr.co/edit/cijSfqcNFdWDZT6UhEZV?p=preview)

Check out the plunkr, click on "New user", note that the best match is chosen as the "directory.users.detail" state (incorrectly).
Now comment any of the states to make them count less than or equal to 10. Click on "New user" again, you'll notice that the best match now is "directory.users.new" (correctly so).

You can test the same plunkr on Firefox for example and you'll notice that the sorting is stable and the result is correct at all times.

Note that the link is using a direct "href" attribute. Using "ui-sref" will work of course because you're directly specifying the state. Using an "href" is the same as reloading the page, I discovered the weird behavior when I was reloading the page.

(Plunkr uses AngularJs, I'm using Angular 4 and seeing the same behavior. Well of course, because angular has nothing to do with this)

Chrome has 2 implementations of `Array#sort` that it flips between depending on the size of the array, one of which uses an unstable sorting algorithm. If it's less than or equal to 10 elements it'll use a stable algorithm. This means, in order to produce valid results at all times we should probably implement our own sorting algorithm [here](https://github.com/ui-router/core/blob/master/src/url/urlRouter.ts#L90).

Some links:
- [Array.sort Sorting Stability in Different Browsers](https://stackoverflow.com/questions/3026281/array-sort-sorting-stability-in-different-browsers)
- [Fast stable sorting algorithm implementation in javascript](https://stackoverflow.com/questions/1427608/fast-stable-sorting-algorithm-implementation-in-javascript)

If you're able to confirm the issue and validate the solution, I can open a PR.

**Comment by mrahhal** [comment]
Is nobody maintaining this repo? 😅 
We're very affected by this issue, right now we have to go through manually updating node_modules files and include the patch.

**Comment by christopherthielen** [comment]
More troublesome is: why are those two routes sorted as the same priority.  `/new` should always sort higher than the same prefix with `/:id`...

**Comment by mrahhal** [comment]
Ah, I was starting to really lose it while debugging this in particular. While I was stepping through the compare function, everything seemed to be good. But then when `Array#sort` returns, the array is magically sorted in an unexpected way. But stable sorting fixed it (no idea why). Really weird.

**Comment by christopherthielen** [comment]
Stable sort is a good idea (i merged it), but not the root cause. I've found the issue (in UrlMatcher.compare).  I also simplified the sorting code to make it easier to debug and will release a fix soon.

**Comment by mrahhal** [comment]
That was my suspicion, I didn't think the unstable sorting itself was the whole problem. Waiting for the fix. Thank you!
