### ISSUE TITLE
`inherit` is documented as having the wrong default value

### ISSUE THREAD

**Issue by mrahhal** [ui-router/core#665]
I spent some time wondering why leaving out inherit leads to the opposite behavior that I expected. It appears that the documented value of `inherit` is wrong [here](https://github.com/ui-router/core/blob/6.0.6/src/transition/interface.ts#L41). It's documented as:

```ts
  /**
   * ...
   * @default `false`
   */
  inherit?: boolean;
```

But looking at [this](https://github.com/ui-router/core/blob/6.0.6/src/params/paramType.ts#L38) shows that it's being set to `true` as a default.

**Comment by christopherthielen** [comment]
fixed, thanks
