### ISSUE TITLE
Child states their childs, show the parent component

### ISSUE THREAD

**Issue by SamanthaAdrichem** [ui-router/core#673]
So I have this state declaration

```
{
    name: 'admin',
    url: '/admin',
    component: AdminDashboardComponent
},
{
    name: 'admin.users',
    url: '/users', // becomes /admin/users due to tree
    component: UsersComponent
},
{
    name: 'admin.users.detail',
    url: '/:userId', // becomes /admin/users/:userId due to tree
    component: UserDetailComponent
},
```

I've changed it to support lazy loading, so you would put the users and users detail inside the users component, (but if needed we can leave it in the root, makes no difference)
So it becomes:

```
// main route file:
{
    name: 'admin',
    url: '/admin',
    component: AdminDashboardComponent
},
{
    name: 'admin.users.**',
    url: '/users',
    loadChildren: () => import('./users/users.module')
        .then((module: {UsersModule: any}) => module.UsersModule),
},

// user routes file
{
    name: 'admin.users',
    url: '/users',
    component: UsersComponent
},
{
    name: 'admin.users.detail',
    url: '/:userId',
    component: UserDetailComponent
},
```

Now when I go to /admin/users/:id it does load the lazy loaded package, but it will just show the `UsersComponent` instead of the `DetailComponent.`

Note that we're actually using the `UIRouterHybrid` package, but i'd imagine this is something core based.

We even tried (since user detail is a new page)
```
// main route file:
{
    name: 'admin',
    url: '/admin',
    component: AdminDashboardComponent
},
{
    name: 'admin.users.**',
    url: '/users',
    loadChildren: () => import('./users/users.module')
        .then((module: {UsersModule: any}) => module.UsersModule),
},
{
    name: 'admin.users.detail.**',
    url: '/users',
    loadChildren: () => import('./users/users/detail/detail.module')
        .then((module: {DetailModule: any}) => module.DetailModule),
},

// user routes file
{
    name: 'admin.users',
    url: '/users',
    component: UsersComponent
},

// detail routes file
{
    name: 'admin.users.detail',
    url: '/:userId',
    component: UserDetailComponent
},
```

And with this one you actually see it lazy load the DetailModule and the users module.. but still show the UsersComponent.

Now 
* If i'd remove lazy-loading it doesn't make a difference
* If I'd change the name of `admin.users.detail` to `admin.user-detail` and then prepend the URL with `/users` everything works fine.. But then it's no longer a proper child in the routing tree.
* If i'd change the URL of the `/users` to `/users/overview` (AND make `admin.users` a dummy route that redirects to overview and `admin.users.overview` the /users route then it does work, but then there is a yuck in the URL.
```
{
    name: 'admin',
    url: '/admin',
    component: AdminDashboardComponent
},
{
    name: 'admin.users',
    url: '/users', // becomes /admin/users due to tree
    redirectTo: 'admin.users.overview'
},
{
    name: 'admin.users.overview',
    url: '/overview', // becomes /admin/users/overview due to tree
    component: UsersComponent
},
{
    name: 'admin.users.detail',
    url: '/:userId', // becomes /admin/users/:userId due to tree
    component: UserDetailComponent
},
```

**Comment by christopherthielen** [comment]
Hi @SamanthaAdrichem 

Nested states in UIRouter usually imply that you also want nested views.  That is, you want `UserDetailComponent` to be rendered *inside* a `UIView` that `UsersComponent` renders.  This style is shown in [Hello Galaxy tutorial](https://ui-router.github.io/ng2/tutorial/hellogalaxy)).  


However, it sounds like you want `UserDetailComponent` to *replace* the `UsersComponent` when `/admin/users/:userid` is active.  There are two common ways to achieve this.    

1) The first is what you've demonstrated in your last snippet, making the list and detail states siblings:

```
{
    name: 'admin.users.overview',
    url: '/', // becomes /admin/users/ due to tree
    component: UsersComponent
},
{
    name: 'admin.users.detail',
    url: '/:userId', // becomes /admin/users/:userId due to tree
    component: UserDetailComponent
},
```
_Note: I changed this to `url: '/'` to avoid `overview` in the url._

2) The second is to keep the parent/child relationship but use view targeting to target the UIView rendered by the `admin` state.

```
{
    name: 'admin',
    url: '/admin',
    component: AdminDashboardComponent
},
{
    name: 'admin.users',
    url: '/users',
    component: UsersComponent
},
{
    name: 'admin.users.detail',
    url: '/:userId',
    views: {
      '@admin': {
        // renders into the unnamed UIView from the 'admin' state.
        // the component from the deepest nested state "wins"
        component: UserDetailComponent
      }
    }
  },
```

**Comment by christopherthielen** [comment]
I've demonstrated view targeting in this [fork of the tutorial](https://stackblitz.com/edit/uirouter-core-issue-673?file=src%2Fconfig%2Fstates.ts)

See [the views guide](https://ui-router.github.io/guide/views#targeting-a-named-uiview) for more details on view targeting

**Comment by SamanthaAdrichem** [comment]
Thank you for the explanation
