### ISSUE TITLE
Navigation to state with slash in parameter call onEnter() twice

### ISSUE THREAD

**Issue by vostrik** [ui-router/core#86]
Navigation to state with slash in parameter call onEnter() twice.
Is this is well known behavior (and I do something wrong) or this is a bug?

**Comment by vostrik** [comment]
Excuse me, Is anyone alive out there?

**Comment by vort3xxx** [comment]
Are you possibly using a globbing pattern in the onenter hook registration criteria?  That would cause it to fire for both the parent and child route.

i.e. /users/*

**Comment by vostrik** [comment]
@vort3xxx No, callback fires twice on one unique url. If I remove parameter with slash — everything is works fine.

**Comment by elboman** [comment]
could you create a [codesandbox](https://codesandbox.io/) to replicate the bug so that we can take a better look?

**Comment by ndeuma** [comment]
Here's a [demo on StackBlitz](https://stackblitz.com/edit/angular-uirouter-bug-demo)
onEnterSubState is called twice, with and without URL encoding for the parameter value:

```
onEnterMainState
onEnterSubState: foo = some/value
onEnterSubState: foo = some%2Fvalue
```

**Comment by wawyed** [comment]
Yes, that definitely doesn't look right. Will try to have a look why this is happening.

**Comment by wawyed** [comment]
Seems to be caused due to the fact that the params are not decoded by the default string ParamTypeDefinition. The way I've solved it in my project was by creating my custom ParamTypeDefinition if you want to have '/' as part of the params.

Something along this lines:
```ts
    urlConfigApi.type('apiLinkType', {
     raw: true,
      encode: (apiLink: string): string => {
        return encodeURIComponent(apiLink);
      },
      decode: (apiLink: string): string => {
        return decodeURIComponent(apiLink);
      },
      pattern: /[^/]*/,
      is: (apiLink: string): boolean => {
        return isString(apiLink);
      },
      equals: (apiLink: string, apiLink2: string): boolean => {
        return isEqual(apiLink, apiLink2);
      }
    });
```

and in your route definition:

```ts
const subState: Ng2StateDeclaration = {
  name: "main.sub",
  url: "sub/:foo", 
  params: {
   foo: {
     type: 'apiLinkType'
  }
 }, 
  onEnter: onEnterSubState
}

```
