### ISSUE TITLE
[Docs] Unfinished sentence

### ISSUE THREAD

**Issue by G07cha** [ui-router/core#88]
I noticed that for [State.StateDeclaration resolve](https://ui-router.github.io/ng1/docs/1.0.0-rc.1/interfaces/state.statedeclaration.html#resolve) property in one of the last paragraphs note for `$stateParams` is not finished([source](https://github.com/ui-router/core/blob/48c5af6/src/state/interface.ts#L244)). I wasn't able to figure out what should be an extension of it so I propose either remove the note or ask @christopherthielen to finish it.

**Comment by christopherthielen** [comment]
why not just read my mind? 😄 just kidding.  This doc has been [updated already](afdeec286b68a5df5d74b7093f682354c40e26ef), but apparently hasn't been published yet.

**Comment by christopherthielen** [comment]
I published the latest docs for AngularJS (version 1.0.10)

**Comment by G07cha** [comment]
Great, thanks!
