### ISSUE TITLE
TS2304: Cannot find name 'object' in common.d.ts

### ISSUE THREAD

**Issue by bbuhler** [ui-router/core#90]
Hi, I'm upgrading a Angular 1 TypeScript project to ui-router 1.0.11.

While replacing `$stateParams` service with `$transition$` I get an error when I import the type definition for that service.

Simplified:
```typescript
import { Transition } from '@uirouter/core';

$stateProvider.state({
  resolve: {
    /** @ngInject */
    conversationItem: function($transition$: Transition) {
      ...
    }
  }
});
```
I checked the `common.d.ts` file:
```typescript
export declare const extend: {
    <T, U>(target: T, source: U): T & U;
    <T, U, V>(target: T, source1: U, source2: V): T & U & V;
    <T, U, V, W>(target: T, source1: U, source2: V, source3: W): T & U & V & W;
    (target: object, ...sources: any[]): any;
};
```
It seems to be fixed when I replace the `target: object` with either `target: Object` or `target: Obj`.

I haven't found that file in in the repository otherwise would have created a PR.

**Comment by christopherthielen** [comment]
What version of typescript are you using? `object` [comes from typescript 2.2](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#object-type)

I guess we've never explicitly stated what version of typescript our type definitions are compatible with

**Comment by bbuhler** [comment]
Yes that was the cause. After updating typescript above 2.2 the error disappears.
Thank you.
