### ISSUE TITLE
build ui-router failure.

### ISSUE THREAD

**Issue by Tony1952466760** [ui-router/core#93]
I want to build ui-router.
mkdir uirouter
cd uirouter
git clone https://github.com/angular-ui/ui-router angularjs
git clone https://github.com/ui-router/core core
cd core
npm install

but failure
![image](https://user-images.githubusercontent.com/11804148/33597318-f9c99a50-d9d9-11e7-9f49-413094b34a82.png)

**Comment by christopherthielen** [comment]
Whoops, thanks for reporting this!  Please try again.
